name: Bezodlesku
favicon: null
layout_spectrum: 0.31010790984146297
typography_spectrum: 0.2990183453075588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25781196681782603
  lightness: 0.16652632202021778
  saturation: 0.4114758465439081
  rhythmicContrast: 0.8229717696085572
purpose: []
